### ISSUE TITLE
Update ProvidedTypes.fs to support Mono 5.0

### ISSUE THREAD

**Issue by dsyme** [YaccConstructor/Brahma.FSharp#75]
See fsprojects/FSharp.TypeProviders.StarterPack#121

**Comment by dsyme** [comment]
@ksmirenko ping :)

**Comment by ksmirenko** [comment]
@dsyme I have applied the required changes [in a separate repository](https://github.com/ksmirenko/Brahma.FSharp/commit/1398b5e949cf1bdd5b9ec4e62f00d3ac2567e63e), but I am expecting difficulties with building the upstream branch on my local machine (possibly due to incorrect GPU drivers/configuration).

We are working with @gsvgit (project owner) to resolve this issue and will merge the changes once we succeed.

**Comment by dsyme** [comment]
Super, thanks! :)

**Comment by ksmirenko** [comment]
I've made a [PR](https://github.com/YaccConstructor/Brahma.FSharp/pull/79). The requested changes are [here](https://github.com/YaccConstructor/Brahma.FSharp/pull/79/files#diff-3ccbf91f0630e57b8b506851331e3283R38); some other project files were changed as well because of Paket.
